### ISSUE TITLE
下载运行报错

### ISSUE THREAD

**Issue by yilianhuaixiao** [moon-studio/vite-vue-bpmn-process#10]
为什么我下载下来不能运行呢？ 
yarn install
yarn dev
各种报错
类似这种
No matching export in "node_modules/@bpmn-io/properties-panel/dist/index.esm.js" for import "FeelTextAreaEntry"

    node_modules/bpmn-js-properties-panel/dist/index.esm.js:3:415:
      3 │ ...psibleEntry, useLayoutState, HeaderButton, ArrowIcon, CreateIcon, DropdownButton, FeelTextAreaEntry } from '@bpmn-io/properties-panel';
        ╵

**Comment by miyuesc** [comment]
换成 npm
