### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by superchangme** [moon-studio/vite-vue-bpmn-process#11]
运行时报了一大堆错，无法运行
Vite Error, /node_modules/.vite/deps/vue.js?v=b3a7f31e optimized info should be defined
Vite Error, /node_modules/.vite/deps/lucide-vue-next.js?v=7cef59f1 optimized info should be defined
Vite Error, /node_modules/.vite/deps/vue.js?v=b3a7f31e optimized info should be defined
Vite Error, /node_modules/.vite/deps/vue.js?v=b3a7f31e optimized info should be defined (x2)
Vite Error, /node_modules/.vite/deps/vue.js?v=b3a7f31e optimized info should be defined (x3)
Vite Error, /node_modules/.vite/deps/vue.js?v=b3a7f31e optimized info should be defined (x4)
Vite Error, /node_modules/.vite/deps/vue.js?v=b3a7f31e optimized info should be defined (x5)

**Comment by miyuesc** [comment]
这种问题建议百度
