### ISSUE TITLE
NaiveUI能替换成element-plus

### ISSUE THREAD

**Issue by nulltrue** [moon-studio/vite-vue-bpmn-process#12]
如题
NaiveUI 怎么好换成element-plus？作者有思路吗？麻烦指导下。

**Comment by wangneal** [comment]
直接把标签换一下就好了呀，我把它改成了antdv

**Comment by nulltrue** [comment]
> 直接把标签换一下就好了呀，我把它改成了antdv

方便加个微信吗？

**Comment by wangneal** [comment]
> > 直接把标签换一下就好了呀，我把它改成了antdv
> 
> 方便加个微信吗？

额，，，加吧，你发

**Comment by tony2y** [comment]
请问解决了吗？
