### ISSUE TITLE
TimerBoundaryEvent节点跟官方的工具比起来好像差一个属性

### ISSUE THREAD

**Issue by ArvinChen9539** [moon-studio/vite-vue-bpmn-process#23]
![image](https://user-images.githubusercontent.com/20532645/208045978-bc8dbb68-297f-4d92-b6e0-f95246ae2fdb.png)
截图里面的这个Details我在系统的界面里面没找到在哪里回显  是不是缺少这部分配置?

**Comment by miyuesc** [comment]
没有，只是我的属性面板没有加这些配置

**Comment by ArvinChen9539** [comment]
明白了,我看config里面
penalMode=default是最全的,需要的话其他属性在custom里面自己加配置就行
![08343736](https://user-images.githubusercontent.com/20532645/208053783-6ef60a62-7f7f-403a-ad60-185630c2b1ce.png)
