### ISSUE TITLE
扩展属性移除无效

### ISSUE THREAD

**Issue by ArvinChen9539** [moon-studio/vite-vue-bpmn-process#24]
![image](https://user-images.githubusercontent.com/20532645/208618729-da196b7b-4d69-4817-9302-4b75c5dd8539.png)
猜测是因为这两个对象不相等没有移除属性导致的
![image](https://user-images.githubusercontent.com/20532645/208618917-d94f66d3-a7a5-4fbd-bb5b-e51fab07f74e.png)
![image](https://user-images.githubusercontent.com/20532645/208618992-40e27f49-0b81-4ac0-9568-8a2b7d969284.png)

我是直接导入一个带有扩展属性的bpmn文件,本地和线上的demo都试了点击移除无效

**Comment by miyuesc** [comment]
已修复
