### ISSUE TITLE
Is there any way to easily enable english for all the labels / text ?

### ISSUE THREAD

**Issue by vesper8** [moon-studio/vite-vue-bpmn-process#31]
Short of manually renaming all the Chinese text to English, is there a better/easier way to have everything in English?

Many thanks

**Comment by songjianet** [comment]
Thank you for your attention to this process engine tool. Our current support for multiple languages is not perfect, so there is no language switching function for the time being.

**Comment by vesper8** [comment]
A switcher would be great, but is there any way at all, such as a translation file.. is there any way at all short of manually renaming labels?

Thanks!

**Comment by songjianet** [comment]
> A switcher would be great, but is there any way at all, such as a translation file.. is there any way at all short of manually renaming labels?
> 
> Thanks!

Do you mean that there is any tool that can change the language one by one without us manually? Our plan is to handle it through https://kazupon.github.io/vue-i18n/zh/.

**Comment by vesper8** [comment]
Yes that would be great.

If you could replace all Chinese hardcoded labels with a call to vue-i18n, so that all labels would be loaded from a translation `zh-cn.json` file. Then it would be really easy to create a `en.json` file.

Do you plan on adding this soon?

Many thanks!

**Comment by labbomb** [comment]
> Yes that would be great.
> 
> If you could replace all Chinese hardcoded labels with a call to vue-i18n, so that all labels would be loaded from a translation `zh-cn.json` file. Then it would be really easy to create a `en.json` file.
> 
> Do you plan on adding this soon?
> 
> Many thanks!

Thank you for your attention, we will add international support as soon as possible
