### ISSUE TITLE
任务节点中的多实例和选择人员还在完善吗？

### ISSUE THREAD

**Issue by tony2y** [moon-studio/vite-vue-bpmn-process#34]
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/38598582/217971381-8c11f239-80e3-49da-8e20-7730cfe74e06.png">

**Comment by miyuesc** [comment]
以后可能会做，但是短时间内不会了

**Comment by tony2y** [comment]
能在element-plus项目中 集成这个吗？

**Comment by miyuesc** [comment]
> 能在element-plus项目中 集成这个吗？

在 elp 中集成这个？？

**Comment by tony2y** [comment]
项目中用的是 elp , 使用不到naive-ui

**Comment by miyuesc** [comment]
。。。首先有个问题，本身这个项目只是作为一个模板项目，演示各种自定义方法和属性面板的基础实现的，具体需求需要你们自己结合项目进行二次开发，我们基本上不会有太多的时间来持续更新和解决属性编辑的问题，组件库更换这个的优先级就更低了

**Comment by falcon-jin** [comment]
> 能在element-plus项目中 集成这个吗？

https://gitee.com/ssllee/my-vite-vue-bpmn-process?_from=gitee_search
