### ISSUE TITLE
Can We Add Custom Element And Shape For Drawing

### ISSUE THREAD

**Issue by TaheriSohrab** [moon-studio/vite-vue-bpmn-process#36]
Hi there, I'm using your source and project, which is a matter of pride.
But I want to add some new custom elements in the change type, like adding some flow beside default flow and conditional flow between elements and drawing the custom shape I wanna add it
Is it possible?
I've been involved with that for a month but couldn't find any solution

with regards

**Comment by miyuesc** [comment]
Thank you for your recognition! 
However, could you provide an example diagram for this issue?

**Comment by TaheriSohrab** [comment]
let me explain more.
I wanna change the connector between two elements like a start event and a gateway, when I click on the connector(the sequence flow) the setting icon which u called CHANGE TYPE I want to add a new connector there beside default flow and conditional flow...and  connectors changes after selecting the custom connector

**Comment by TaheriSohrab** [comment]
![vite](https://user-images.githubusercontent.com/51846650/220080699-9677ad46-2ab7-4790-958f-78cea05a68a3.png)

**Comment by miyuesc** [comment]
So, you mean you want to add a custom type of sequence flow and add it to the 'Switch Type' menu, right?

**Comment by TaheriSohrab** [comment]
Yes yesss, absolutely is it possible?

**Comment by miyuesc** [comment]
Sure, its possible.

First, you need to add a JSON schema for your custom shape. Then, you should inherit the BpmnRenderer.js to write an SVG node creation method for this shape. Lastly, you need to modify the original BpmnReplaceOptions.js and BpmnReplace.js .


The JSON schema, you can reference my SQL Node.

**Comment by miyuesc** [comment]
As for BpmnReplaceOptions and BpmnReplace, you can just inherit from BpmnReplace and implement a new replacement module that overwrites the original module when you use it.

**Comment by TaheriSohrab** [comment]
thanks so muchhhh for your attention, time, and explanation
I go for it now and check it out to see what can I do after ur explanations
thanks a lot...I'll be in touch with you and share the result...

**Comment by TaheriSohrab** [comment]
I cannot find your JSON schema template in your code and don't know how to add the new custom shape to the change element...
would you please give me a directory of your project or describe it crystal-clear to me...
I like to make it English and other languages  and make pull requests for ur project to appreciate you

**Comment by miyuesc** [comment]
Emmm... I think you can find the answer here [bpmn-js-examples/custom-meta-model](https://github.com/bpmn-io/bpmn-js-examples/blob/master/custom-meta-model/README.md)

**Comment by TaheriSohrab** [comment]
thanks so much I'm reading and checking it...I'll be in touch with you..
anyway your response and attention are so valuable to me
