### ISSUE TITLE
Color Picker for context pad

### ISSUE THREAD

**Issue by TaheriSohrab** [moon-studio/vite-vue-bpmn-process#37]
hi there I wanna add a color picker to the context pad  and change the color of the connectors by clicking on the color which is selected from the color palette popup

**Comment by TaheriSohrab** [comment]
that's very very important to me
any idea could be helpful for me

**Comment by miyuesc** [comment]
https://github.com/bpmn-io/bpmn-js-color-picker

**Comment by TaheriSohrab** [comment]
i see this

**Comment by miyuesc** [comment]
It has nothing to do with Vite

**Comment by TaheriSohrab** [comment]
let me check again
I'll be in touch with u via email if is it possible later
you are one of the best and respectful developers I ever meet
thanks for your responsibilities

**Comment by TaheriSohrab** [comment]
could u please check your email

**Comment by TaheriSohrab** [comment]
it's too important to me

**Comment by TaheriSohrab** [comment]
I really need to add a color picker to the context pad at the moment and if is it possible to add some custom shapes in ' change type '
I'm open-armed to pay for it if you can do it for me
is it possible to you please
the company put so much pressure on me for this
