### ISSUE TITLE
color picker in context pad

### ISSUE THREAD

**Issue by TaheriSohrab** [moon-studio/vite-vue-bpmn-process#38]
I really need to add a color picker to the context pad at the moment and if is it possible to add some custom shapes in ' change type '
I'm open-armed to pay for it if you can do it for me
is it possible for to you, please
the company put so much pressure on me for this

**Comment by miyuesc** [comment]
The "bpmn-js-color-picker" repository already provides color picker in the context pad; you can refer to it directly in additionalModules when `new Modeler()`. Documentation is provided in the Readme documentation for this repository.

**Comment by miyuesc** [comment]
colorPicker has been added to the project in the morning. 

As for your other question about adding other custom shapes to the contextPad, which custom form exactly?

**Comment by TaheriSohrab** [comment]
the color picker added to the context pad now?
I wanna add some custom shape which company designed to the context pad

**Comment by TaheriSohrab** [comment]
yesss i have saw ittt
it added to the contextPad
thanks a lot you are amazinggggg
can I add a custom shape to the context pad like this:::

![vite](https://user-images.githubusercontent.com/51846650/222881652-c91d4c61-fc38-4912-97e5-1af2099237e3.png)
