### ISSUE TITLE
custom element to context pad

### ISSUE THREAD

**Issue by TaheriSohrab** [moon-studio/vite-vue-bpmn-process#39]
Hi there I saw your latest update for the color picker and it's amazing thanks for your attention and updating.
the last thing I'm involved with is this::

![vite](https://user-images.githubusercontent.com/51846650/222892416-53e363e4-3999-4599-9a75-565786d88189.png)

Can we add some custom elements we are designing with the draw ability?

**Comment by miyuesc** [comment]
I think this is a custom requirement and should not be supported in this project. 

But bpmn.js does have an official example to help you implement a custom shape, it just needs some modifications to add it to the changeMenu menu

**Comment by TaheriSohrab** [comment]
I've already change and add custom shape in bpmn.dev.js
but I can't see my changes om the display...
should I change sth else?
or use npm install to modify the changes or sth?

**Comment by miyuesc** [comment]
You need to modify the ReplaceMenuProvider and ReplaceOptions files in bpmn.js

**Comment by TaheriSohrab** [comment]
let me check again so
thankss

**Comment by TaheriSohrab** [comment]
do u have an email to contact u instead of opening a new issue if needed?

**Comment by miyuesc** [comment]
I only have a QQ email：913784771@qq.com

**Comment by TaheriSohrab** [comment]
I sent u an email to u now  did u received?
