### ISSUE TITLE
Can I load saved data on table?

### ISSUE THREAD

**Issue by TaheriSohrab** [moon-studio/vite-vue-bpmn-process#43]
Hi I have created a custom component and Util for showing on the panel...
I can save and load entered value for each property completely.
but I can not show saved and loaded data on the table
I mean this:

![issue](https://user-images.githubusercontent.com/51846650/232300334-3385ade5-adf5-47fe-b79a-491450224592.png)

solving this issue will be my end step
I really need this issue complete
please help me

**Comment by miyuesc** [comment]
Custom attributes require writing your own JSON schema file. And then, u can use modeling.updateProperties or modeling.updateModdleProperties to save.

https://github.com/bpmn-io/bpmn-js-examples/blob/master/properties-panel-extension/app/descriptors/magic.json

https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel-extension

**Comment by TaheriSohrab** [comment]
I'll Check the links you shared...thanks so much Galaxy
