### ISSUE TITLE
编辑流程的属性，控制台有报错

### ISSUE THREAD

**Issue by 4color** [moon-studio/vite-vue-bpmn-process#48]
![image](https://github.com/moon-studio/vite-vue-bpmn-process/assets/20277116/fb7a7d8c-b805-42c0-b03d-b11f91704948)

![image](https://github.com/moon-studio/vite-vue-bpmn-process/assets/20277116/6c98b0da-121b-4277-becf-1b338326aacc)

但是你的演示址不会报错。

**Comment by miyuesc** [comment]
别对 bpmn 相关的任何实例进行响应式处理

**Comment by 4color** [comment]
我是刚下来的zip文件，clone下来的也一样。

**Comment by sillyhtw** [comment]
比如修改流程名称，直接使用element.businessObject.set('name', value)进行赋值，替换掉modeling?.updateProperties(element, { name: value })，就可以避免报错。（如果ts类型检查报错，垓下Element的导入，从bpmn导入）， 其他属性（id,isExecutable,version）类似。

**Comment by RelaxAndNotIndulge** [comment]
> 比如修改流程名称，直接使用element.businessObject.set('name', value)进行赋值，替换掉modeling?.updateProperties(element, { name: value })，就可以避免报错。（如果ts类型检查报错，垓下Element的导入，从bpmn导入）， 其他属性（id,isExecutable,version）类似。

这个方案好像不行，比如流程Id和流程名称按照这个方案修改了，触发不了这个监听

![image](https://github.com/moon-studio/vite-vue-bpmn-process/assets/32625268/b0d1c446-ede5-4255-97a7-ff9a7b0bf7b4)

**Comment by RelaxAndNotIndulge** [comment]
> ![image](https://user-images.githubusercontent.com/20277116/254521377-fb7a7d8c-b805-42c0-b03d-b11f91704948.png)
> 
> ![image](https://user-images.githubusercontent.com/20277116/254521418-6c98b0da-121b-4277-becf-1b338326aacc.png)
> 
> 但是你的演示址不会报错。

@4color 请问现在解决了吗？怎么解决的？  @miyuesc 大神请问什么时候帮忙修复一下这个问题呢？

**Comment by miyuesc** [comment]
已处理

**Comment by miyuesc** [comment]
已处理

**Comment by RelaxAndNotIndulge** [comment]
@miyuesc 请问怎么处理的呢？代码预计什么时候能提交一下？

**Comment by miyuesc** [comment]
> @miyuesc 请问怎么处理的呢？代码预计什么时候能提交一下？

拉代码
