### ISSUE TITLE
流程设计点击元素右侧属性面板页面部分更新不及时

### ISSUE THREAD

**Issue by xiaoyu-666** [moon-studio/vite-vue-bpmn-process#50]
![屏幕截图 2023-08-18 115121](https://github.com/moon-studio/vite-vue-bpmn-process/assets/27267958/126bc777-1d12-42e9-b1e5-4d4f888e7958)

你好，我点击左面第一流程SequenceFlow是属性面板没有条件设置的，右边三个SequenceFlow是有条件设置的
1、当我点击左面第一个SequenceFlow元素是，右面属性面板没有条件设置是正确的，然后我点击右面三个带分支条件的SequenceFlow的元素，结果属性面板不显示条件条件设置，只有全部取消元素选中状态，再点击右面三个SequenceFlow就会重新出现
2、相反，先点击右面三个SequenceFlow的任意一个SequenceFlow元素，属性面板出现条件设置是正确的，但是里面的值更新后切换其他SequenceFlow会出现值不更新情况，之后再点击左面第一个SequenceFlow的元素，发现属性面板带有条件设置，这是错误的

**Comment by RocketM** [comment]
在components/Panel/index.tsx中增加对selection.changed事件的监听即可解决该问题，具体代码可参考官方的属性面板
```javascript
// (2a) selection changed
  useEffect(() => {
    const onSelectionChanged = (e) => {
      const { newSelection = [] } = e;

      if (newSelection.length > 1) {
        return _update(newSelection);
      }

      const newElement = newSelection[0];

      const rootElement = canvas.getRootElement();

      if (isImplicitRoot(rootElement)) {
        return;
      }

      _update(newElement || rootElement);
    };

    eventBus.on('selection.changed', onSelectionChanged);

    return () => {
      eventBus.off('selection.changed', onSelectionChanged);
    };
  }, []);
```

> 源代码：[bpmn-js-properties-panel](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/2dec27cdad14b579d0f51e18260a555058e6ea04/src/render/BpmnPropertiesPanel.js#L83)
