### ISSUE TITLE
vue3版本没有多实例设置页签

### ISSUE THREAD

**Issue by hjtjiajia** [moon-studio/vite-vue-bpmn-process#56]
vue3版本flowable没有多实例设置页签，是不支持吗

**Comment by miyuesc** [comment]
支持，只是这个项目里面没有实现。

**Comment by YukiYuko** [comment]
> 支持，只是这个项目里面没有实现。

请问一下如何实现 给个思路 谢谢大佬

**Comment by miyuesc** [comment]
> > 支持，只是这个项目里面没有实现。
> 
> 请问一下如何实现 给个思路 谢谢大佬

@YukiYuko 参考 https://juejin.cn/column/6964382482007490590
