### ISSUE TITLE
我需要添加任务监听器，应该参考哪部分文档呢

### ISSUE THREAD

**Issue by zukxu** [moon-studio/vite-vue-bpmn-process#9]
![image](https://user-images.githubusercontent.com/63381545/180904474-faa161b0-8c41-4d1e-b7e0-743a5917fd14.png)
我需要用户任务中添加指定用户，任务监听等操作，该参考哪些文档呢？

**Comment by wangneal** [comment]
我是照着执行监听器加的，等大佬回复

**Comment by miyuesc** [comment]
> 我是照着执行监听器加的，等大佬回复

可以，本身也都差不多
